In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("final_data.csv")

In [3]:
dataset

,age,experience_years_total,experience_years_in_field,num_skills,annual_salary_usd,has_equity,equity_vesting_years,vacation_weeks,overtime_hours_per_month,months_since_last_promotion,...,primary_tech_field,job_title,employment_type,work_arrangement,education_level,languages_spoken,skills,primary_skill,certifications,company_size
0,32.0,7.7,3.2,3.0,100290.66,0.0,0.0,3.0,12.9,38.0,...,Backend Development,Platform Engineer,Full-time,Remote,Associate's Degree,English,Spring Boot; PHP; Python,Spring Boot,0,Small (11-50)
1,30.0,3.0,1.9,8.0,92383.12,1.0,1.0,4.0,6.5,26.0,...,QA & Testing,QA Engineer,Full-time,On-site,Bootcamp,English; Telugu,PyTest; API Testing; Cypress; JUnit; Postman; ...,PyTest,0,Startup (1-10)
2,32.0,0.5,0.5,8.0,107153.59,1.0,4.0,5.0,13.2,0.0,...,Backend Development,API Engineer,Full-time,Remote,Bachelor's Degree,English; German; Spanish; Dutch,PHP; Express.js; Java; Rust; Spring Boot; C#; ...,PHP,AWS Certified Solutions Architect,Enterprise (1000+)
3,31.0,14.5,12.4,4.0,217074.54,1.0,1.0,2.0,5.9,111.0,...,Database & Data Engineering,Analytics Engineer,Full-time,Hybrid,Bootcamp,English; German; Mandarin,Snowflake; Elasticsearch; Cassandra; dbt,Snowflake,Linux Foundation Certified,Medium (51-200)
4,42.0,7.9,3.8,4.0,152246.34,0.0,0.0,6.0,0.0,20.0,...,Embedded Systems & IoT,Embedded Engineer,Full-time,Fully Remote,Bootcamp,English; Telugu,RTOS; ARM; PCB Design; Embedded Linux,RTOS,0,Startup (1-10)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,38.0,6.2,3.9,6.0,218700.43,1.0,4.0,3.0,7.3,52.0,...,Product Management,Associate Product Manager,Full-time,Fully Remote,Bootcamp,English,Jira; Confluence; Wireframing; SQL; Agile; Roa...,Jira,0,Large (201-1000)
9996,37.0,9.7,7.0,6.0,170835.76,0.0,0.0,5.0,8.4,58.0,...,Full-Stack Development,Full Stack Developer,Full-time,On-site,Bootcamp,English,GraphQL; Python; Vue.js; REST APIs; Docker; Mo...,GraphQL,Certified Scrum Master; Azure Solutions Architect,Small (11-50)
9997,31.0,0.5,0.5,5.0,25695.15,1.0,3.0,4.0,17.1,0.0,...,Full-Stack Development,Senior Software Engineer,Full-time,Remote,Bachelor's Degree,English,TypeScript; Redis; REST APIs; PostgreSQL; Python,TypeScript,0,Startup (1-10)
9998,32.0,8.7,8.3,8.0,264531.10,0.0,0.0,4.0,14.3,78.0,...,Data Science & ML,Data Scientist,Full-time,Hybrid,Bootcamp,English; Bengali,OpenCV; SQL; Keras; Python; R; PyTorch; scikit...,OpenCV,Kubernetes CKA,Enterprise (1000+)
9999,33.0,6.3,2.5,5.0,163072.71,1.0,4.0,0.0,11.1,11.0,...,Frontend Development,UI Engineer,Part-time,Fully Remote,Master's Degree,English; Tamil,HTML/CSS; TypeScript; Vue.js; Webpack; GraphQL,HTML/CSS,0,Small (11-50)

In [4]:
dataset.columns

Index(['age', 'experience_years_total', 'experience_years_in_field',
       'num_skills', 'annual_salary_usd', 'has_equity', 'equity_vesting_years',
       'vacation_weeks', 'overtime_hours_per_month',
       'months_since_last_promotion', 'num_previous_companies',
       'job_satisfaction_score', 'is_actively_looking', 'employee_id',
       'first_name', 'last_name', 'gender', 'location', 'currency',
       'primary_tech_field', 'job_title', 'employment_type',
       'work_arrangement', 'education_level', 'languages_spoken', 'skills',
       'primary_skill', 'certifications', 'company_size'],
      dtype='object')

In [5]:
dataset = pd.get_dummies(dataset, dtype=int,drop_first='True')

In [6]:
#for col in dataset.columns:
    #print(col)

In [7]:
print(dataset['is_actively_looking'])

0       0.0
1       0.0
2       1.0
3       0.0
4       0.0
       ...
9995    0.0
9996    0.0
9997    0.0
9998    0.0
9999    0.0
Name: is_actively_looking, Length: 10000, dtype: float64

In [8]:
indep_X = dataset.drop(columns=['is_actively_looking'])
dep_Y = dataset['is_actively_looking']

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y , test_size = 1/3, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
from sklearn.model_selection import GridSearchCV

param_grid = {'solver':['newton-cg', 'lbfgs', 'liblinear', 'saga'],
             'penalty':['l2']} 



grid = GridSearchCV(LogisticRegression(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

In [13]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [14]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'penalty': 'l2', 'solver': 'newton-cg'}: 0.7184750895239846

In [15]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[2680    5]
 [ 648    1]]

In [16]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

         0.0       0.81      1.00      0.89      2685
         1.0       0.17      0.00      0.00       649

    accuracy                           0.80      3334
   macro avg       0.49      0.50      0.45      3334
weighted avg       0.68      0.80      0.72      3334

In [17]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.501764353123126

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,130.855591,4.806963,2.111508,0.677314,l2,newton-cg,"{'penalty': 'l2', 'solver': 'newton-cg'}",0.705726,0.706551,0.706551,0.706551,0.705515,0.706179,0.000460,1
1,64.051336,22.109469,1.513015,0.509500,l2,lbfgs,"{'penalty': 'l2', 'solver': 'lbfgs'}",0.654339,0.655924,0.686078,0.706551,0.676587,0.675896,0.019532,2
2,82.454574,19.230659,0.971070,0.167345,l2,liblinear,"{'penalty': 'l2', 'solver': 'liblinear'}",0.071931,0.070026,0.074413,0.076160,0.076625,0.073831,0.002516,3
3,293.174115,19.830841,0.153629,0.167848,l2,saga,"{'penalty': 'l2', 'solver': 'saga'}",0.071931,0.070026,0.072883,0.077686,0.076406,0.073786,0.002845,4

In [22]:
new_data = pd.DataFrame(np.zeros((1, len(indep_X.columns))),columns=indep_X.columns)

In [23]:
new_data = sc.transform(new_data)

In [25]:
age_input=float(input("Age:"))
experience_years_total_input=float(input("Experience:"))
Skills_input=float(input("No.of skills:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
annual_salary_usd_input=float(input("Annual Salary(USD):"))

Age: 38
Experience: 3
No.of skills: 3
Sex Male 0 or 1: 1
Annual Salary(USD): 112567

In [26]:
Future_Prediction = grid.predict(new_data)
print(Future_Prediction)

[0.]

In [32]:
# Save the best trained Logistic Regression model
pickle.dump(grid.best_estimator_, open("finalized_model_logistic.sav", "wb"))

In [33]:
# Save the StandardScaler
pickle.dump(sc, open("scaler.sav", "wb"))

In [34]:
print("Model and Scaler Saved Successfully!")

Model and Scaler Saved Successfully!

In [35]:
# LOAD THE MODEL

In [36]:
import pickle
import pandas as pd
import numpy as np

loaded_model = pickle.load(open("finalized_model_logistic.sav", "rb"))
loaded_scaler = pickle.load(open("scaler.sav", "rb"))

print("Model Loaded Successfully!")

Model Loaded Successfully!